In [1]:
import torch

In [2]:
orders_weight = torch.nn.Parameter(
                torch.ones(3, 1) / 3, requires_grad=True)

In [3]:
orders_weight.shape

torch.Size([3, 1])

In [4]:
orders_weight[0]

tensor([0.3333], grad_fn=<SelectBackward>)

In [5]:
orders_weight[1]

tensor([0.3333], grad_fn=<SelectBackward>)

In [6]:
orders_weight[2]

tensor([0.3333], grad_fn=<SelectBackward>)

In [7]:
a = torch.randn(4, 4)
a

tensor([[ 1.3135,  0.2595, -1.9706, -0.9544],
        [-1.5111, -1.1697, -0.3257,  0.2257],
        [ 1.6242, -2.0578,  2.0254,  0.7361],
        [ 1.1691, -0.8997, -0.8939,  0.5465]])

In [8]:
b = torch.randn(4, 4)
b

tensor([[ 0.7312, -0.9582,  0.5702,  2.0466],
        [-0.3067, -0.1239,  0.6115, -0.7665],
        [-0.7246,  1.4005, -0.7701,  1.5462],
        [ 0.9401,  0.5655, -0.7777,  0.6500]])

In [9]:
a + b

tensor([[ 2.0447, -0.6987, -1.4004,  1.0923],
        [-1.8177, -1.2936,  0.2857, -0.5408],
        [ 0.8996, -0.6573,  1.2553,  2.2823],
        [ 2.1093, -0.3342, -1.6716,  1.1965]])

In [12]:
orders_weight_matrix = torch.nn.Parameter(
            torch.DoubleTensor(5, 5), requires_grad=True
        )
orders_weight_matrix

Parameter containing:
tensor([[3.9383e-316, 3.9399e-316,  1.4004e+00,  1.0923e+00,  1.8177e+00],
        [ 1.2936e+00,  2.8575e-01,  5.4083e-01,  8.9964e-01,  6.5727e-01],
        [ 1.2553e+00,  2.2823e+00,  2.1093e+00,  3.3418e-01,  1.6716e+00],
        [ 1.1965e+00, 9.4861e-322, 2.3715e-322, 3.9387e-316,  0.0000e+00],
        [4.9407e-324,  0.0000e+00,  0.0000e+00, 1.6304e-322, 3.9397e-316]],
       dtype=torch.float64, requires_grad=True)

In [13]:
torch.nn.init.kaiming_normal_(orders_weight_matrix, mode='fan_out')
orders_weight_matrix

Parameter containing:
tensor([[-0.8432,  0.3291,  0.3464, -0.6963, -0.9024],
        [ 0.6049,  0.4622,  0.0476, -0.0341,  0.1942],
        [-0.1722,  0.2471, -1.1739,  0.6064, -0.2839],
        [ 0.9791, -0.6894,  0.9598,  0.4448,  0.6002],
        [ 0.6891, -0.4457,  0.5473,  0.2621,  0.4509]], dtype=torch.float64,
       requires_grad=True)

In [15]:
res = torch.ones(5, 2)
res

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
test = orders_weight_matrix[0].unsqueeze(1)
test

tensor([[-0.8432],
        [ 0.3291],
        [ 0.3464],
        [-0.6963],
        [-0.9024]], dtype=torch.float64, grad_fn=<UnsqueezeBackward0>)

In [25]:
test * res

tensor([[-0.8432, -0.8432],
        [ 0.3291,  0.3291],
        [ 0.3464,  0.3464],
        [-0.6963, -0.6963],
        [-0.9024, -0.9024]], dtype=torch.float64, grad_fn=<MulBackward0>)