In [1]:
import torch

In [2]:
orders_weight = torch.nn.Parameter(
                torch.ones(3, 1) / 3, requires_grad=True)

In [3]:
orders_weight.shape

torch.Size([3, 1])

In [4]:
orders_weight[0]

tensor([0.3333], grad_fn=<SelectBackward0>)

In [5]:
orders_weight[1]

tensor([0.3333], grad_fn=<SelectBackward0>)

In [6]:
orders_weight[2]

tensor([0.3333], grad_fn=<SelectBackward0>)

In [7]:
a = torch.randn(4, 4)
a

tensor([[-0.0279, -0.2113, -0.8118, -0.7086],
        [ 0.9160, -1.1179, -0.2762,  0.8881],
        [ 0.7319,  0.2534, -0.1805,  1.2127],
        [ 1.0765,  0.2475, -1.1733, -0.0962]])

In [8]:
b = torch.randn(4, 4)
b

tensor([[-0.3038, -1.7850, -0.0053, -0.3630],
        [ 0.3969, -0.0670,  1.8740,  1.5088],
        [ 1.1239,  2.4896, -0.7959, -0.3130],
        [ 0.0159,  1.5910, -1.2453,  0.1444]])

In [9]:
a + b

tensor([[-0.3316, -1.9963, -0.8171, -1.0717],
        [ 1.3128, -1.1849,  1.5979,  2.3968],
        [ 1.8559,  2.7430, -0.9764,  0.8997],
        [ 1.0925,  1.8384, -2.4185,  0.0481]])

In [10]:
orders_weight_matrix = torch.nn.Parameter(
            torch.DoubleTensor(5, 5), requires_grad=True
        )
orders_weight_matrix

Parameter containing:
tensor([[ 0.0000e+00,  0.0000e+00, 4.3840e-316, 3.5495e-316, 6.9199e-310],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, 4.9407e-324,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, 4.9407e-324, 7.8342e-154, 1.1129e-308],
        [3.1620e-322, 5.5829e-322, 4.3853e-316, 4.3857e-316, 1.0398e-312]],
       dtype=torch.float64, requires_grad=True)

In [11]:
torch.nn.init.kaiming_normal_(orders_weight_matrix, mode='fan_out')
orders_weight_matrix

Parameter containing:
tensor([[ 0.2409, -0.6716, -0.9996, -0.6675,  0.0817],
        [-0.4881, -0.9464,  0.4677, -0.6312, -0.2927],
        [-0.3802, -0.3800, -0.0728, -0.4675,  0.1590],
        [-0.6491,  0.8401,  0.8943, -0.9798,  0.3391],
        [-0.2442,  0.5653, -0.6031, -0.2897,  0.5965]], dtype=torch.float64,
       requires_grad=True)

In [12]:
res = torch.ones(5, 2)
res

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
test = orders_weight_matrix[0].unsqueeze(1)
test

tensor([[ 0.2409],
        [-0.6716],
        [-0.9996],
        [-0.6675],
        [ 0.0817]], dtype=torch.float64, grad_fn=<UnsqueezeBackward0>)

In [14]:
test * res

tensor([[ 0.2409,  0.2409],
        [-0.6716, -0.6716],
        [-0.9996, -0.9996],
        [-0.6675, -0.6675],
        [ 0.0817,  0.0817]], dtype=torch.float64, grad_fn=<MulBackward0>)

In [22]:
diag_weight = torch.nn.Parameter(
            torch.ones(5, 1) / 5, requires_grad=True
        )
diag_weight

Parameter containing:
tensor([[0.2000],
        [0.2000],
        [0.2000],
        [0.2000],
        [0.2000]], requires_grad=True)

In [23]:
diag_matrix = torch.diag(diag_weight)
diag_matrix

tensor([0.2000], grad_fn=<DiagBackward0>)

In [24]:
a = torch.randn(3)
a

tensor([-1.1095, -1.1183,  1.0090])

In [25]:
torch.diag(a)

tensor([[-1.1095,  0.0000,  0.0000],
        [ 0.0000, -1.1183,  0.0000],
        [ 0.0000,  0.0000,  1.0090]])

In [27]:
eye1 = torch.eye(3)
eye1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [28]:
eye1 * a

tensor([[-1.1095, -0.0000,  0.0000],
        [-0.0000, -1.1183,  0.0000],
        [-0.0000, -0.0000,  1.0090]])

In [29]:
m = torch.randn(3, 3)
m

tensor([[ 0.7771, -0.3956,  0.2993],
        [-2.9271, -2.1777, -0.9230],
        [-0.8522, -1.2203,  0.5841]])

In [32]:
a

tensor([-1.1095, -1.1183,  1.0090])

In [30]:
a * m

tensor([[-0.8622,  0.4424,  0.3020],
        [ 3.2475,  2.4353, -0.9313],
        [ 0.9455,  1.3646,  0.5893]])

In [33]:
b = eye1 * a
b

tensor([[-1.1095, -0.0000,  0.0000],
        [-0.0000, -1.1183,  0.0000],
        [-0.0000, -0.0000,  1.0090]])

In [34]:
b * m

tensor([[-0.8622,  0.0000,  0.0000],
        [ 0.0000,  2.4353, -0.0000],
        [ 0.0000,  0.0000,  0.5893]])

In [38]:
a

tensor([-1.1095, -1.1183,  1.0090])

In [37]:
at = a.t()
at

tensor([-1.1095, -1.1183,  1.0090])

In [43]:
test = torch.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
test

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [44]:
a

tensor([-1.1095, -1.1183,  1.0090])

In [45]:
a * test

tensor([[-1.1095, -1.1183,  1.0090],
        [-1.1095, -1.1183,  1.0090],
        [-1.1095, -1.1183,  1.0090]])

In [48]:
b = a[0,:]

IndexError: too many indices for tensor of dimension 1

In [47]:
test * a.t()

tensor([[-1.1095, -1.1183,  1.0090],
        [-1.1095, -1.1183,  1.0090],
        [-1.1095, -1.1183,  1.0090]])

In [49]:
test = torch.randn(3, 3)
test

tensor([[ 1.0283, -1.7010,  1.2992],
        [ 0.0132,  0.9743, -1.1289],
        [ 1.2019, -0.9452, -0.4877]])

In [50]:
a = torch.tensor([1, 2, 3])
diag = torch.eye(3) * a
diag

tensor([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 3.]])

In [51]:
diag * test

tensor([[ 1.0283, -0.0000,  0.0000],
        [ 0.0000,  1.9487, -0.0000],
        [ 0.0000, -0.0000, -1.4632]])

In [52]:
test * diag

tensor([[ 1.0283, -0.0000,  0.0000],
        [ 0.0000,  1.9487, -0.0000],
        [ 0.0000, -0.0000, -1.4632]])

In [54]:
test

tensor([[ 1.0283, -1.7010,  1.2992],
        [ 0.0132,  0.9743, -1.1289],
        [ 1.2019, -0.9452, -0.4877]])

In [53]:
a * test

tensor([[ 1.0283, -3.4021,  3.8975],
        [ 0.0132,  1.9487, -3.3868],
        [ 1.2019, -1.8904, -1.4632]])

In [56]:
test.t() * a

tensor([[ 1.0283,  0.0264,  3.6058],
        [-1.7010,  1.9487, -2.8357],
        [ 1.2992, -2.2579, -1.4632]])

In [66]:
p = torch.nn.Parameter(torch.tensor([[1], [10], [100], [1000], [10000]]), requires_grad=True)
print(p.shape)
p

torch.Size([5, 1])


Parameter containing:
tensor([[0.2000],
        [0.2000],
        [0.2000],
        [0.2000],
        [0.2000]], requires_grad=True)

In [61]:
pt = p.t()
print(pt.shape)
pt

torch.Size([1, 5])


tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000]], grad_fn=<TBackward0>)

In [62]:
m = torch.randn(5, 5)
m

tensor([[ 0.9360,  1.9201,  0.7680,  1.0529, -0.6830],
        [-1.4596, -0.4174, -0.7066, -0.3612, -1.4705],
        [ 0.3340,  1.4583,  1.2612,  0.5761, -0.2948],
        [-0.5545,  1.1322, -0.0589,  0.0483,  2.2213],
        [-1.6251, -0.8226,  0.5873,  3.0184, -0.9087]])

In [63]:
m * p

tensor([[ 0.1872,  0.3840,  0.1536,  0.2106, -0.1366],
        [-0.2919, -0.0835, -0.1413, -0.0722, -0.2941],
        [ 0.0668,  0.2917,  0.2522,  0.1152, -0.0590],
        [-0.1109,  0.2264, -0.0118,  0.0097,  0.4443],
        [-0.3250, -0.1645,  0.1175,  0.6037, -0.1817]], grad_fn=<MulBackward0>)

In [67]:
pt * m

tensor([[ 0.1872,  0.3840,  0.1536,  0.2106, -0.1366],
        [-0.2919, -0.0835, -0.1413, -0.0722, -0.2941],
        [ 0.0668,  0.2917,  0.2522,  0.1152, -0.0590],
        [-0.1109,  0.2264, -0.0118,  0.0097,  0.4443],
        [-0.3250, -0.1645,  0.1175,  0.6037, -0.1817]], grad_fn=<MulBackward0>)

In [68]:
p * m

tensor([[ 0.1872,  0.3840,  0.1536,  0.2106, -0.1366],
        [-0.2919, -0.0835, -0.1413, -0.0722, -0.2941],
        [ 0.0668,  0.2917,  0.2522,  0.1152, -0.0590],
        [-0.1109,  0.2264, -0.0118,  0.0097,  0.4443],
        [-0.3250, -0.1645,  0.1175,  0.6037, -0.1817]], grad_fn=<MulBackward0>)