In [6]:
import torch

In [7]:
m = torch.ones(5, 5)
m

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
a = torch.tensor([1, 2, 3, 4, 5])
a = a.unsqueeze(1)
print(a.shape)
print(a)

torch.Size([5, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [9]:
a * m

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.]])

In [10]:
m * a.t()

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

In [ ]:
a.t() * m