In [1]:
import torch

In [2]:
orders_weight = torch.nn.Parameter(
                torch.ones(3, 1) / 3, requires_grad=True)

In [3]:
orders_weight.shape

torch.Size([3, 1])

In [4]:
orders_weight[0]

tensor([0.3333], grad_fn=<SelectBackward>)

In [5]:
orders_weight[1]

tensor([0.3333], grad_fn=<SelectBackward>)

In [6]:
orders_weight[2]

tensor([0.3333], grad_fn=<SelectBackward>)

In [7]:
a = torch.randn(4)
a

tensor([ 0.3724,  0.6175, -1.4634, -0.0643])

In [ ]:
b = torch.randn(4)